### ISSUE TITLE
design + create gmail overlay passphrase window + allow simple signup passwords

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#100]
we will need a simple passphrase prompt. This might show in some cases in gmail main window, as an absolutely positioned iframe with our own page in it, asking for a passphrase.

```
Please enter your passphrase to read encrypted email
[x] forget passphrase when I close Chrome
[....................] [ok] [later]
```

**Comment by mondo989** [comment]
Something that looks like this?
![testmodal](https://cloud.githubusercontent.com/assets/3431871/14068455/ed1baee8-f438-11e5-8933-b509773fe72b.png)

Is this passphrase prompt for when the user receives an email and does not have pgp?

**Comment by tomholub** [comment]
Nope, this is when user decides to protect all their encrypted email by a passphrase (which is normally the case). Then they need passphrase to read it or download attachments

In terms of the elements, yes it would be something of that sort

**Comment by tomholub** [comment]
If they say "Later", something would need to show instead of the email itself that it cannot be shown, and a button to enter passphrase again.

**Comment by tomholub** [comment]
There would probably be white semi-transparent overlay over the rest of gmail around this

**Comment by mondo989** [comment]
Got ya. When would the user see this?
First time logging in?

I guess I'm wondering which file should the modal be placed in?

**Comment by tomholub** [comment]
They will see it the first time there is a message to decrypt since they opened the browser. 

Eg every time you restart the browser, you will see this, if you open a message that is encrypted.

for the iframe content, I suggest `src/chrome/gmail_elements/passphrase.htm`. For integrating the frame into gmail, that we would do later

**Comment by tomholub** [comment]
You can use similar elements and styles from the settings pages and setup, that we have already styled

**Comment by mondo989** [comment]
I've added passphrase.htm in gmail elements folder.

I was able to recycle quite a bit of the code. 
(By using the body id of "settings").

<img width="1218" alt="screen shot 2016-03-28 at 1 37 55 pm" src="https://cloud.githubusercontent.com/assets/3431871/14089562/5088c662-f4ea-11e5-81db-2acffa8313b2.png">

I've added in a fixed passphrase box and a fixed overlay (with lower z-index)

Maybe we remove the back arrow?

**Comment by tomholub** [comment]
Looks great! I would say remove the arrow, and also add

[x] Remember passphrase for this session
already pre-checked

also, if someone wanted to change settings and remember passphrase for all
time (like it is now), there should be a subtle link to settings, maybe
call it "passphrase preferences" or something like that.

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Updated passphrase.

<img width="953" alt="screen shot 2016-03-28 at 6 30 10 pm" src="https://cloud.githubusercontent.com/assets/3431871/14095264/4e829ec8-f513-11e5-989d-f366490a4370.png">

**Comment by mondo989** [comment]
For passphrase preferences, were you talking about adding it to the settings?

<img width="1014" alt="screen shot 2016-03-28 at 6 34 30 pm" src="https://cloud.githubusercontent.com/assets/3431871/14095310/cb516e0c-f513-11e5-862f-a7fd5a7ffb4b.png">

**Comment by tomholub** [comment]
Yes something like that. For now, I'm just randomly listing things in the
settings because I don't know all the things that will need to go there. So
additions will look kind of like that.

In the future, we'll have to do a complete settings redesign, once we know
what goes in

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
the result came out very nice!

![2016-04-08-105815_1183x874_scrot](https://cloud.githubusercontent.com/assets/6306961/14373056/e847b47c-fd78-11e5-87b5-bf6a47350eb7.png)


![2016-04-08-105822_1183x874_scrot](https://cloud.githubusercontent.com/assets/6306961/14373055/e841c1e8-fd78-11e5-8904-4be74e579fcd.png)

For now this is only for users of "advanced setup".
