### ISSUE TITLE
Pushing "tab" or "return" when typing in an address (of a recent contact) does nothing.

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#105]
<img width="566" alt="screen shot 2016-03-28 at 6 47 23 pm" src="https://cloud.githubusercontent.com/assets/3431871/14095478/933adcb8-f515-11e5-99d5-4e8cea6d4134.png">

I'd imagine that pushing tab/return after typing out the first few letters should update with the selected recipient.

**Comment by tomholub** [comment]
yup agree
