### ISSUE TITLE
logo on new message should be padded from the right side

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#109]
I didn't know how to give the background "10px from right side" position, or something like that.

![2016-03-31-203655_709x844_scrot](https://cloud.githubusercontent.com/assets/6306961/14175905/b68875f0-f780-11e5-8ff5-9c1fa841199b.png)

Might need one more element that can be positioned absolutely

**Comment by mondo989** [comment]
Yeah just adding an image tag that's absolutely positioned is a bit better, especially if the window size will be dynamic later on. 

<img width="548" alt="screen shot 2016-04-01 at 10 28 28 am" src="https://cloud.githubusercontent.com/assets/3431871/14211587/7dc5c85c-f7f4-11e5-8930-e8c2d1553d9b.png">

**Comment by tomholub** [comment]
Yes it's actually dynamic because reply box uses the same css. So when
making changes to send box, one has to cross check the affect on reply box
as well

**Comment by mondo989** [comment]
Good catch.

<img width="643" alt="screen shot 2016-04-02 at 1 24 34 pm" src="https://cloud.githubusercontent.com/assets/3431871/14227953/44d3ca34-f8d6-11e5-80d1-0dfea7358b01.png">

**Comment by tomholub** [comment]
looks good :)
