### ISSUE TITLE
 color inconsistency

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#110]
we use several different shades of green:
 - square compose button
 - send button
 - email address bubble
 - new secure email header
 - in the logo images themselves

we should agree on one shade and make it consistent, something like a primitive style guide

![2016-03-31-211251_709x844_scrot](https://cloud.githubusercontent.com/assets/6306961/14176810/8dcb7c0c-f785-11e5-9d4d-9a22c75426a5.png)

**Comment by tomholub** [comment]
![2016-04-08-110334_665x874_scrot](https://cloud.githubusercontent.com/assets/6306961/14373136/8dbbce2a-fd79-11e5-9e16-85d099b3753f.png)

**Comment by tomholub** [comment]
for now

**Comment by mondo989** [comment]
Cool, this works. 
I'll be able to get to more assigned things by Sun/Mon.

**Comment by mondo989** [comment]
I'd say we are good here for now.
