### ISSUE TITLE
Sending encrypted email button's image is broken

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#111]
Not sure why, I pulled latest

<img width="90" alt="screen shot 2016-04-01 at 9 59 18 am" src="https://cloud.githubusercontent.com/assets/3431871/14210832/6f4d484e-f7f0-11e5-8cc3-e870dd81a183.png">

**Comment by tomholub** [comment]
whoops. check now

**Comment by mondo989** [comment]
I pulled and still get the extra feature...

<img width="1193" alt="screen shot 2016-04-04 at 9 55 10 pm" src="https://cloud.githubusercontent.com/assets/3431871/14269173/177a60c6-fab0-11e5-8379-c2ca293724ab.png">

**Comment by tomholub** [comment]
fixed it, thanks!
