### ISSUE TITLE
move css in htm files to cryptup.css

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#112]
in `pgp_block.htm` and `attachment.htm`

**Comment by mondo989** [comment]
Looking at the code for pgp_block.htm and attachment.htm

It looks as if it repeats the same code... 
As the body has the same properties as the inline css.

<img width="794" alt="screen shot 2016-04-10 at 2 03 05 pm" src="https://cloud.githubusercontent.com/assets/3431871/14411983/1ec47ece-ff25-11e5-9292-31d4df589aa4.png">


Same with attachment.htm
<img width="762" alt="screen shot 2016-04-10 at 2 05 06 pm" src="https://cloud.githubusercontent.com/assets/3431871/14411990/4c1eeed6-ff25-11e5-8603-d080531ab285.png">


I am just removing the css, we should be all good here.

**Comment by tomholub** [comment]
looks good
