### ISSUE TITLE
custom checkboxes

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#116]
is there any good libraries to customize checkboxes? I added zoom to them to be bigger, but they are not looking the best

![image](https://cloud.githubusercontent.com/assets/6306961/14403740/60d6b3da-fe95-11e5-83f3-0e96cd360ac8.png)
(Feedback by Christopher)

**Comment by mondo989** [comment]
Here's a link to one...

http://codepen.io/bbodine1/pen/novBm

<img width="1250" alt="screen shot 2016-04-10 at 2 57 58 pm" src="https://cloud.githubusercontent.com/assets/3431871/14412273/b2dc1d36-ff2c-11e5-92a8-208ec55e7073.png">

Maybe the SquaredOne one?

Here's another version of svg's but it's a little excessive
http://tympanus.net/Development/AnimatedCheckboxes/

Let me know if you have any preference.

**Comment by tomholub** [comment]
looks quite nice! I like square one and four. Might also do the rounded, in
which case rounded one + square one makes sense.

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Doing some styling and implementing the boxes...

<img width="1179" alt="screen shot 2016-04-18 at 8 18 10 pm" src="https://cloud.githubusercontent.com/assets/3431871/14623721/bed1df28-05a2-11e6-80db-c85fa1bfce2e.png">

**Comment by mondo989** [comment]
Pushed some changes for this... 

I don't really like the flow of input, checkbox, input checkbox. I wonder if we can work on the way that the content is structured on these two with the checkboxes.

**Comment by mondo989** [comment]
Here's another for Setup CryptUP

<img width="799" alt="screen shot 2016-04-19 at 11 57 55 pm" src="https://cloud.githubusercontent.com/assets/3431871/14663091/aad9e19e-068a-11e6-97dd-3f9bd74a7873.png">

I plan to use this custom check box styling throughout. 

Let me know any feedback or anything otherwise.

**Comment by tomholub** [comment]
looks very nice!

**Comment by mondo989** [comment]
Cool, I would like to revisit some of these and maybe redesign some.
The flow of a few of these are off, I feel like we can improve on a few these... on a later date.
