### ISSUE TITLE
On reply, user should have option to remove the person they are replying to 

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#120]
<img width="533" alt="screen shot 2016-04-10 at 4 54 48 am" src="https://cloud.githubusercontent.com/assets/3431871/14409014/6b38294c-fed8-11e5-9123-627d576c8153.png">

It seems counterintuitive, but it would probably be upsetting for the users that couldn't change their mind.

**Comment by tomholub** [comment]
agree
