### ISSUE TITLE
When we show the user their pgp key, have an indicator (down chevron) to show them that they need to scroll more to see their key.

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#121]
Probably more of an optimization, but it would be helpful when I need a copy of my key, I might not instinctively know to scroll down.

<img width="719" alt="screen shot 2016-04-10 at 1 57 51 pm" src="https://cloud.githubusercontent.com/assets/3431871/14411953/74d56d6a-ff24-11e5-9332-cd5c41817549.png">

**Comment by tomholub** [comment]
or maybe add a "copy pubkey" button above it?

**Comment by tomholub** [comment]
or also.. put it into a fixed height scrolling div. That way it's maybe even clearer

**Comment by tomholub** [comment]
closing for new restyled settings
