### ISSUE TITLE
On reply, when adding a user who doesn't have pgp, the question doesn't appear.

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#122]
Cannot style the Question in reply, 
See attached.

<img width="699" alt="screen shot 2016-04-10 at 3 14 10 pm" src="https://cloud.githubusercontent.com/assets/3431871/14412362/2cdc0f7c-ff2f-11e5-88b3-82e3bf346674.png">

When I send the message
<img width="904" alt="screen shot 2016-04-10 at 3 16 48 pm" src="https://cloud.githubusercontent.com/assets/3431871/14412368/4dc19446-ff2f-11e5-8b05-e5c3cb306538.png">

**Comment by tomholub** [comment]
closed in 97023a8
