### ISSUE TITLE
Loader/Spinner styling

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#123]
Loader feels a bit dated.

<img width="572" alt="screen shot 2016-04-10 at 3 08 07 am" src="https://cloud.githubusercontent.com/assets/3431871/14412399/d9b9dec2-ff2f-11e5-8619-07a39c6e6a9c.png">

Can we update the spinner to something a bit more sexier (svg) and call it in?
- Cool inspiration:
  http://codepen.io/aurer/pen/jEGbA
  http://samherbert.net/svg-loaders/

**Comment by tomholub** [comment]
absolutely!

**Comment by tomholub** [comment]
I just noticed the new spinner in setup.. looks great!

**Comment by mondo989** [comment]
Hey @tomholub, plan on getting back in the groove and pushing code this weekend.

**Comment by tomholub** [comment]
@mondo989 Myself I'll try to get more first hand feedback like we did with Geo, that way we'll know what's most important to improve first
