### ISSUE TITLE
redesign settings to better match user behavior

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#136]

**Comment by mondo989** [comment]
Can you provide me a little more information on this?

What do you mean by matching user behavior?

**Comment by tomholub** [comment]
Right now, settings are just a collection of random buttons. I want to figure out what people do most often and offer that on main screen, and then have other screens with less common stuff. I have to think about this one a bit more to figure out what exactly is needed.. right now it's just temporary

![2016-04-21-003425_890x1056_scrot](https://cloud.githubusercontent.com/assets/6306961/14682576/d1b41a9a-0758-11e6-8787-fe85ed464779.png)

**Comment by mondo989** [comment]
Ok cool, let me know. 
I think having users testing/using the product would help some as well.

**Comment by tomholub** [comment]
agree, that's what I plan to do back in SF
