### ISSUE TITLE
too long composed new message requires a scroller

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#144]
right now it will cut the iframe contents out

**Comment by mondo989** [comment]
It looks as if Gmail makes the height of the message larger, as well as gives the scroller.
<img width="656" alt="screen shot 2016-04-20 at 12 40 03 am" src="https://cloud.githubusercontent.com/assets/3431871/14663583/8593afc2-0690-11e6-993e-2155824652f0.png">

**Comment by mondo989** [comment]
Fixed, we have a scroller that appears.

<img width="618" alt="screen shot 2016-04-20 at 12 44 23 am" src="https://cloud.githubusercontent.com/assets/3431871/14663636/1962b590-0691-11e6-9c1c-270041a15322.png">

**Comment by tomholub** [comment]
that's great!

**Comment by tomholub** [comment]
actually the scroller didn't get pushed into the code.. can you check?

**Comment by mondo989** [comment]
Weird, I left it out... Re-pushed it though and tested again :)

**Comment by mondo989** [comment]
<img width="617" alt="screen shot 2016-04-20 at 1 53 06 pm" src="https://cloud.githubusercontent.com/assets/3431871/14684717/40e206ac-06ff-11e6-9697-afac07ffc5ae.png">


Very interesting that I can copy and paste and it takes the properties of what i copied and pasted. lol

**Comment by tomholub** [comment]
Yeah I'm not super sure if that's a bug or a feature :D

**Comment by tomholub** [comment]
Can the scroller be hidden until it's needed? I might achieve that in javascript but maybe pure css can help?
