### ISSUE TITLE
include a visual guide in welcome email

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#149]
eg where to click on first email, etc.

**Comment by mondo989** [comment]
If you can help to come up with the wording/copy you want to use, I can work on the design of it and then we can implement it in an email. 
I have a few tested templates that we can use as a base, if interested.

**Comment by tomholub** [comment]
I'd leave it as a plain white email with screenshots, for now. Just basic steps how to send and receive encrypted msgs. Later we can improve the visuals as needed

**Comment by tomholub** [comment]
it looks like this for now 
![2016-05-10-173656_1182x1080_scrot](https://cloud.githubusercontent.com/assets/6306961/15166653/e35c87c8-16d5-11e6-8948-862050ff46f1.png)
