### ISSUE TITLE
When entering in multiple recipients, using TAB it moves the focus to the subject line

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#151]
With gmail and other email clients when I push tab after typing out some of the address, it autocompletes, and recipient line stays focused, and I can type in another email address.

Currently whenever I press tab or click on the user's name, by default the focus goes to subject.

<img width="584" alt="screen shot 2016-04-19 at 11 45 48 pm" src="https://cloud.githubusercontent.com/assets/3431871/14662943/38f5e18c-0689-11e6-858d-8acc903773b6.png">
 
The experience would improve if it stayed focused on the recipient. 
The above image would also be better if it stayed focused and prompting the user that they can continue to type.

What do you think?

**Comment by tomholub** [comment]
I agree, related to #105 - both should work as gmail

**Comment by mondo989** [comment]
Heh. My apologies for the duplicate, I'm just really used to, and want to, send emails that way.  :)

**Comment by tomholub** [comment]
Kk, I'll fix the issue #105 in the current milestone, 100% agree

**Comment by mondo989** [comment]
So much smoother with sending... :)
