### ISSUE TITLE
Restyling (the prompt) when recipients don't have CryptUP or other PGP

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#152]
The prompt with the options could use a little love.

<img width="582" alt="screen shot 2016-04-20 at 1 01 14 am" src="https://cloud.githubusercontent.com/assets/3431871/14663878/693feb08-0693-11e6-8d2c-b5ddc9a67034.png">

Let me know what you think.

**Comment by mondo989** [comment]
Here's what I thinking:

<img width="846" alt="screen shot 2016-04-20 at 12 51 24 am" src="https://cloud.githubusercontent.com/assets/3431871/14663904/a9198d4c-0693-11e6-8255-c7d36b09913f.png">

I swapped the challenge question and pubkey around.
I'm making an assumption that users will be more likely to ask a question over adding a pubkey.
Do you think users are more inclined to use the challenge question or add the pubkey?

**Comment by tomholub** [comment]
Looks great! Experienced users would use pubkey, less experienced challenge question. I can actually guess who is who (based on who used advanced setup) so I can put the correct one on left side. This looks perfect, good work.

**Comment by mondo989** [comment]
Cool, I'll implement it!

**Comment by tomholub** [comment]
Can you get to this in the next few days? That would be awesome :) otherwise I can move it to another milestone

**Comment by tomholub** [comment]
@mondo989 *

**Comment by mondo989** [comment]
Been traveling a bit the past couple of days, will complete by the weekend.

**Comment by tomholub** [comment]
Kk great

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
looks awesome

![2016-05-09-180953_610x738_scrot](https://cloud.githubusercontent.com/assets/6306961/15132710/44be078c-1611-11e6-808b-6d9aa0694895.png)

**Comment by mondo989** [comment]
:)

On Mon, May 9, 2016 at 6:10 PM, Tom James Holub <notifications@github.com>
wrote:

> Closed #152 <https://github.com/tomholub/cryptup-chrome/issues/152>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tomholub/cryptup-chrome/issues/152#event-655156384>
>



-- 
Armando Flores
Armando.sx
