### ISSUE TITLE
traditional drafts mid-convo can create issues

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#153]
![2016-04-21-000631_1058x1056_scrot](https://cloud.githubusercontent.com/assets/6306961/14681735/fd06fb30-0754-11e6-8bc3-4ea29755267a.png)

**Comment by mondo989** [comment]
Yeah I guess I don't fully get drafts yet...

Will there be another folder like gmail?
Or will it be inline with the email conversation thread?

**Comment by tomholub** [comment]
can you click on reply box in a convo and show me the window? It should say saving/saved on the bottom  - draft status
