### ISSUE TITLE
fast message switching bug - hijacking wrong convo

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#154]
Not sure if this is a duplicate, but the cryptup button hijacked my usual reply button.

<img width="1250" alt="screen shot 2016-04-20 at 1 40 55 pm" src="https://cloud.githubusercontent.com/assets/3431871/14684387/b7e78b48-06fd-11e6-97b2-f1ca4bd10f23.png">
<img width="1295" alt="screen shot 2016-04-20 at 1 39 04 pm" src="https://cloud.githubusercontent.com/assets/3431871/14684389/b7ea2f06-06fd-11e6-8a73-4f587613f005.png">
<img width="1274" alt="screen shot 2016-04-20 at 1 38 53 pm" src="https://cloud.githubusercontent.com/assets/3431871/14684388/b7e88f7a-06fd-11e6-9291-d1f980500dcc.png">

As a regular gmail user, this is quite a bit upsetting. :( 
Maybe we can move it to the left or another place? 

I have to refresh each time I want to reply all (for regular gmail)

**Comment by tomholub** [comment]
It's a bug, try latest version & let me know

**Comment by tomholub** [comment]
actually, does it get fixed when you navigate out and back in? I did notice, testing it now, when switching between messages fast, similar things can happen, but get fixed on second try (need to debug it before release)

**Comment by mondo989** [comment]
Yeah, I pulled the latest, it's fixed. I'm happy again. :)

<img width="320" alt="screen shot 2016-04-21 at 10 40 16 pm" src="https://cloud.githubusercontent.com/assets/3431871/14730152/0cfe1fec-0812-11e6-97e6-bdcc60b9046f.png">

**Comment by tomholub** [comment]
When you click on the left/right arrow in a conversation on top right, it will switch to another thread. If you do it many times, with some pgp conversations and some not, sometimes the wrong convo will get reply box replaced. For me to fix
