### ISSUE TITLE
When replying, and adding a new user, the Question/Add pub prompt key needs to be fluid for window size

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#164]
<img width="1411" alt="screen shot 2016-05-09 at 6 12 30 pm" src="https://cloud.githubusercontent.com/assets/3431871/15132747/a5f3f782-1611-11e6-89b4-06ec991ab3ea.png">

**Comment by mondo989** [comment]
<img width="763" alt="screen shot 2016-05-21 at 12 18 36 pm" src="https://cloud.githubusercontent.com/assets/3431871/15450364/48e0865a-1f4e-11e6-9637-a2044eeeb871.png">
<img width="1207" alt="screen shot 2016-05-21 at 12 18 09 pm" src="https://cloud.githubusercontent.com/assets/3431871/15450365/48e15d28-1f4e-11e6-9770-dfa87f1d42ab.png">

**Comment by tomholub** [comment]
works like a charm
