### ISSUE TITLE
photoshop designs for new settings

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#171]
Send email(similar for help and feedback):
 - just a lightbox with one paragraph and iframe where I put sending window

Security:
 - [ ] require a pass phrase to open encrypted email
 - Passphrase strength: [##########_______] Time to crack: years 
 - [Change passphrase]

Backup (mostly as is now):
 - "1 backup found, your gmail is backed up correctly"
 - ... all backup options here

Keyserver:
 - whatever is in KEYSERVER STATUS now

Contacts:
 - whatever is in CONTACTS now

My Keys:
 - table of keys with buttons, and selecting a primary key, and showing which is primary key, as we doodled

**Comment by mondo989** [comment]
Here's our whiteboard notes from basic settings:
![img_2432](https://cloud.githubusercontent.com/assets/3431871/15309344/03b2115e-1b9b-11e6-8c35-914fd0a88358.JPG)


Here's a draft for the basic Settings:

![basic-settings](https://cloud.githubusercontent.com/assets/3431871/15309320/cd0bf1c4-1b9a-11e6-8bed-1ef731494da6.png)


Let me know if you have any feedback

**Comment by tomholub** [comment]
Yes the draft roughly works, I'm thinking to do it icon-only and put words
below the squares.​ I think it might be nicer

**Comment by mondo989** [comment]
With and without the circles

<img width="813" alt="screen shot 2016-05-17 at 2 34 52 pm" src="https://cloud.githubusercontent.com/assets/3431871/15340096/8cc0de20-1c3c-11e6-88f9-0eed83e777e2.png">
<img width="1106" alt="screen shot 2016-05-17 at 2 33 12 pm" src="https://cloud.githubusercontent.com/assets/3431871/15340097/8cd26d66-1c3c-11e6-8370-a781b1bfe961.png">

**Comment by tomholub** [comment]
I like the one w/o circles! Also switch to advanced version and help, and I
think that will work well.

I'd probably call the first one just "New email".

Can you pls also add the photoshop assets somewhere in the repo. Maybe make
a folder /design next to /src, so that if we change color palette later, it
would be easy to modify

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Sure no problem. 

And yeah, the advanced settings and help would be included.

**Comment by tomholub** [comment]
ispiration
![image](https://cloud.githubusercontent.com/assets/6306961/15341196/2599f8e8-1c42-11e6-994b-5925b46a44eb.png)

**Comment by mondo989** [comment]
All psd's are included in the repo.
With the light boxes we can style as we insert the content. 

Are we all set here?

<img width="1262" alt="screen shot 2016-05-19 at 1 40 32 pm" src="https://cloud.githubusercontent.com/assets/3431871/15450376/cfa902ac-1f4e-11e6-9910-93610bacef32.png">

<img width="1226" alt="screen shot 2016-05-21 at 12 23 56 pm" src="https://cloud.githubusercontent.com/assets/3431871/15450384/ee412fc8-1f4e-11e6-9a16-7a5754a26fc8.png">

<img width="611" alt="screen shot 2016-05-19 at 1 40 11 pm" src="https://cloud.githubusercontent.com/assets/3431871/15450377/d22435a6-1f4e-11e6-9c04-14638c327b78.png">

**Comment by tomholub** [comment]
yes I think we're set!

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
I will close this, and we can continue in #172

**Comment by tomholub** [comment]
great work
