### ISSUE TITLE
basic/raw html templates for new settings

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#172]

**Comment by mondo989** [comment]
Hey Tom,

I've pushed a new folder that will contain the updated settings file and stylesheet.
There's still quite a few things left for me to work out in terms of styling and layout content.  

Although, toggling (basic/advanced) settings, and toggling accounts is setup using Jquery, let me know if you have any feedback on the way it's being setup.

**Comment by tomholub** [comment]
Looks very nice, I can definitely use this to put the functionality in,
perfect!

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
<img width="1329" alt="screen shot 2016-05-23 at 10 34 47 am" src="https://cloud.githubusercontent.com/assets/3431871/15478896/0b9d4df2-20d2-11e6-978b-f5bce095fede.png">


Here's how it looks coded.

**Comment by tomholub** [comment]
Very nice, this is great

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Are we good to close it here?

**Comment by tomholub** [comment]
definitely

**Comment by mondo989** [comment]
<img width="383" alt="screen shot 2016-05-24 at 1 24 52 pm" src="https://cloud.githubusercontent.com/assets/3431871/15518878/c0ed55f8-21b3-11e6-8517-a8ab9bc1e702.png">
