### ISSUE TITLE
extension window for settings / email / help instead of directly to settings

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#174]

**Comment by mondo989** [comment]
I was playing around from what we had on the whiteboard...

<img width="899" alt="screen shot 2016-05-16 at 6 30 21 pm" src="https://cloud.githubusercontent.com/assets/3431871/15308636/446d8dce-1b94-11e6-9433-bec2062c101a.png">


A)

<img width="1342" alt="screen shot 2016-05-16 at 6 16 42 pm" src="https://cloud.githubusercontent.com/assets/3431871/15308457/77947980-1b92-11e6-90e0-0c31b3bc71c5.png">


B)

<img width="1179" alt="screen shot 2016-05-16 at 6 29 40 pm" src="https://cloud.githubusercontent.com/assets/3431871/15308641/561b1726-1b94-11e6-8fbb-95437d583ec8.png">

**Comment by tomholub** [comment]
I like the first one, and I'm considering to remove the Help, and just make
the settings cog bigger and write settings under it, to make it a bit less
cluttered, and I think it'll be very good :) try see what happens

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Cool, I agree. 

We can just have send new email and settings.

**Comment by tomholub** [comment]
@mondo989 I connected it but check it out, it will need some TLC :)

![2016-05-25-195957_1064x1056_scrot](https://cloud.githubusercontent.com/assets/6306961/15562403/afd0e068-22b3-11e6-864b-138ad8f66479.png)

**Comment by mondo989** [comment]
Awwww yeaaaah! :)
