### ISSUE TITLE
experimenting with colors + secure lines

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#179]
color to experiment with: `59A72C`
unify color for secure iframes: `4px solid 59A72C`

**Comment by tomholub** [comment]
@mondo989 do you want to experiment with some color alternatives? then we can test them across my and your screen to see how it looks

**Comment by mondo989** [comment]
Sure! I can update the color to the Hex.

Although, I am not sure what you mean on the secure lines.

**Comment by tomholub** [comment]
I'll take care of those, mostly try to find out which color will fit the
best with the gmail white background, in terms of the button and new
message header

(compared to standard gmail theme)

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Cool got ya. 

I'm working away from SH today, will you be available/around sometime tomorrow? 
(Before we meet with Gio)

**Comment by tomholub** [comment]
yup absolutely, I'll arrive sometime noon to 1pm

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Perfect!

**Comment by mondo989** [comment]
Interesting when I swap out the default green with the new one.

<img width="1155" alt="screen shot 2016-05-24 at 12 44 39 pm" src="https://cloud.githubusercontent.com/assets/3431871/15517577/5802ec2a-21ad-11e6-9eea-7748ca77d4c3.png">

It swapped out some of the colors for the gradient

**Comment by mondo989** [comment]
Playing with the gradient color.

**Comment by mondo989** [comment]
Using the same gradient, as above...
Maybe it's a bit too harsh in the beginning, but uses #59A72C


<img width="553" alt="screen shot 2016-05-24 at 1 45 29 pm" src="https://cloud.githubusercontent.com/assets/3431871/15519345/e02a2ec6-21b5-11e6-81a1-af6b1105e17d.png">
