### ISSUE TITLE
When sending a new message, opening Gmail every time, is painful

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#185]
Playing around with an idea let me know any feedback,

When a user clicks the cryptup extension menu icon, we show the active profile and settings icon in the lower right hand corner. (The send secure message button/copy size is a bit exaggerated)

<img width="1175" alt="screen shot 2016-05-26 at 3 31 19 pm" src="https://cloud.githubusercontent.com/assets/3431871/15592264/21a9a550-2357-11e6-8149-de33b96062c1.png">

When the user clicks send secure message we show (recycled) elements from inside chrome with an overlay/lightbox.

<img width="1043" alt="screen shot 2016-05-26 at 3 07 23 pm" src="https://cloud.githubusercontent.com/assets/3431871/15591742/ab2ec1ec-2353-11e6-883e-f4d1018fe1a0.png">

**Comment by tomholub** [comment]
I can do overlay only on gmail page, not on elsewhere. But we can fit the new message box into the bubble. That might work.

**Comment by mondo989** [comment]
That would actually work perfect.

**Comment by mondo989** [comment]
<img width="376" alt="screen shot 2016-05-27 at 6 55 21 pm" src="https://cloud.githubusercontent.com/assets/3431871/15624482/77c44f76-243d-11e6-9a88-7b779df94959.png">

Roughly designed with placeholder elements, you should be able to access.

**Comment by mondo989** [comment]
Hey @tomholub, I am trying to toggle a class with JS, onclick, although it doesn't seem to work from the extensions menu.

**Comment by tomholub** [comment]
hey I'm not sure about selecting the account there. Because it gets more complicated as to which should be set when - active window, last used, etc? I'd just leave it out.. 

If the email will be sent within that window, I can have the select it later (send-from). 

I'd simplify it back to [send secure email] + [settings]

**Comment by tomholub** [comment]
@mondo989 I've made experimental one, that lets you select email after clicking on [send secure email]. Let's not style it yet, as I'm not sure if it will stay.. just experimenting.

I'm thinking, I can always skip this step if you have currently gmail open - then I just use the same one. In other cases I'll let the user choose. Same for settings. 

But as saying, for now it's experimental :)
