### ISSUE TITLE
remove inonicons :(

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#189]
it still would only load sometimes.. I've had it debugging it :/

it has something to do with having ionicons locally/offline. We have to load it locally for security, but it has issues.

for settings/contacts, can you please change it to (we use ionicons): http://www.flaticon.com/free-icon/contact-cards_12674#term=contacts&page=2&position=64

and then we'll have to work on replacing the rest with FA or something, unless we can figure it out

**Comment by mondo989** [comment]
Yeah it's really weird. I've tried z-index and it's still random. 

For the contacts icon, I updated it to the SVG. 
Maybe we consider just using individual SVG's?

**Comment by tomholub** [comment]
Yeah exactly.. just svgs and font awesome
