### ISSUE TITLE
clicking on manual gmail backup does nothing

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#203]
![2016-10-16-072114_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6306961/19418068/2a558f7c-9371-11e6-8885-4970a9e9a199.png)

![2016-10-16-072117_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6306961/19418067/2a5062e0-9371-11e6-82a2-d07ee9ed1fee.png)

**Comment by mondo989** [comment]
Howdy there! :)
