### ISSUE TITLE
Close button on email composer doesn't actually close

### ISSUE THREAD

**Issue by chejazi** [tomholub/cryptup-chrome#212]
Close button not closing email composer (modal editor, not inline reply editor)
Chrome 54.0.2840.98
OSX 10.11.2

Confirmed on multiple gmail accounts (1 university, 1 personal)

**Comment by tomholub** [comment]
Do you see any errors in the console when trying to close? This is usually a symptom showing that something else failed in Javascript exec

**Comment by chejazi** [comment]
Heh, it closes now :)

**Comment by tomholub** [comment]
Sometimes it would fail to close when it just updated (needs gmail window refresh). I'll try to see if I can make it not even open

**Comment by tomholub** [comment]
(plugin updated)

**Comment by tomholub** [comment]
@chejazi it was actually a bug, but it would only happen sometimes. The worst kind of bugs, right. #215
