### ISSUE TITLE
cannot encrypt for some keys

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#214]
VM456 compose.js:224 Error: Error encrypting message: Could not find valid key packet for encryption in key .............

**Comment by tomholub** [comment]
relying on https://github.com/openpgpjs/openpgpjs/issues/503

**Comment by tomholub** [comment]
closed for #345

**Comment by falemagn** [comment]
I get this problem too, but gpg doesn't list they key as expired. What can I do to help debug the issue?

**Comment by falemagn** [comment]
Here we go. I've anonymized it, to protect the recipient from spam and his privacy too.

```
(1) Primary keys found: 1  
(2) ----- Testing key 0 -----  
(3) PK 0 > Is Private? [-] false  
(4) PK 0 > User id 0: [-] John Doe <some1@email.com>  
(5) PK 0 > User id 1: [-] John Doe <some2@email.com>  
(6) PK 0 > User id 2: [-] John Doe <some3@email.com>  
(7) PK 0 > Primary User: [-] John Doe <some2@email.com>  
(8) PK 0 > Fingerprint: [-] 275E F2DC 902A BE21 1A0F 44DB F0DF 7E95 CAA2 5245  
(9) PK 0 > Subkeys: [-] 1  
(10) PK 0 > Primary key algo: [-] dsa  
(11) PK 0 > Primary key verify: [-] 3: expired  
(12) PK 0 > Primary key creation? [-] 1047727537 or 2003-03-15T11:25:37.000Z  
(13) PK 0 > Primary key expiration? [-] -  
(14) PK 0 > Encrypt/Decrypt test: Got error performing encryption/decryption test: Error: Error encrypting message: Could not find valid key packet for encryption in key f0df7e95caa25245  
(15) PK 0 > SK 0 > LongId: [-] 0C831009B223AA25  
(16) PK 0 > SK 0 > Created: [-] 1047727537 or 2003-03-15T11:25:37.000Z  
(17) PK 0 > SK 0 > Algo: [-] elgamal  
(18) PK 0 > SK 0 > Verify: [-] 0: expired  
(19) PK 0 > SK 0 > Subkey tag: [-] 14  
(20) PK 0 > SK 0 > Subkey getBitSize: [-] 4096  
(21) PK 0 > SK 0 > Subkey decrypted: [-] null  
(22) PK 0 > SK 0 > Binding signature length: [-] 0  
(23) PK 0 > internal dateBeforeExpiration: [-] undefined  
(24) PK 0 > internal usableButExpired: [-] false  
```
I see now that even though gpg lets me encrypt stuff, it does give an error when checking the key:

```
$ gpg --edit-key some1@email.com
gpg (GnuPG) 2.2.4; Copyright (C) 2017 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


pub  dsa1024/F0DF7E95CAA25245
     created: 2003-03-15  expires: never       usage: SC  
     trust: ultimate      validity: ultimate
sub  elg4096/0C831009B223AA25
     created: 2003-03-15  expires: never       usage: E   
[ultimate] (1). John Doe <some2@email.com>
[ultimate] (2)  John Doe <some1@email.com>
[ultimate] (3)  John Doe <some3@email.com>

gpg> check
key F0DF7E95CAA25245: 16 signatures not checked due to missing keys
```
In case the problem lies with the key, it would be very appreciated if you told me what could I suggest his owner to do. 

Thanks a lot.

**Comment by tomholub** [comment]
I'm not exactly sure without seeing the key itself. The person could try to just remove all users and signatures, then make new ones using gpg. That should work.

**Comment by falemagn** [comment]
I've googled for _"signatures not checked due to missing keys"_ and this thread came up which seems to fit with what I am getting:
https://gnupg-users.gnupg.narkive.com/ApM6MM6n/suddenly-can-t-verify-my-key-s-signatures

Thus, the gpg check seems to be harmless and should still allow for the key to be used.

Did you get any useful info from the "OpenPGP compatibility" check?

**Comment by tomholub** [comment]
Sort of, but the information is somewhat conflicting. 

```
(11) PK 0 > Primary key verify: [-] 3: expired  
(12) PK 0 > Primary key creation? [-] 1047727537 or 2003-03-15T11:25:37.000Z  
(13) PK 0 > Primary key expiration? [-] -  
```
If it's expired, I would have thought it could tell me when it's expired. 

I won't have time to investigate it further for now. Feel free to create a new issue, ideally if you could also share the public key there. If you don't want to share our publicly, then you can send it to human@flowcrypt.com with link to my comment here. Thanks!

**Comment by falemagn** [comment]
Thanks Tom! I've sent the key to the address you mentioned.
