### ISSUE TITLE
think about pgp fingerprints as images - for verification

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#218]

**Comment by exceptionwhisperer** [comment]
Use Facial recognition api from amazon aws service. Pictures and faces can be identified using there engine. The user gets the email. If the sender chooses to check a box that says use additional verification. The connection to the aws. amazon does this A engine is used to validate pictures and objects. Once connected the far end would have to show there face or a object of choice to prove its them. One issue  is that the account connect for the group has to have all of the pictures uploaded so the service uses those it has to validate the object. The assumption is that using a device that has a camera would prompt the user to display there face, or a specific object to be recognized. This would act as a additional layer of security. What amazon has created is powerful but the api well. The picture of whatever you choose and how the end point would know what to show  would have to be worked out. As to be fair you could hold up that persons face in a photo if that was the know object to be used but assume thats not the object that is being looked for.

**Comment by tomholub** [comment]
@exceptionwhisperer thanks for input, I'll look into it

**Comment by tomholub** [comment]
Displaying public key fingerprints as words instead, to compare easily. This is mostly a feature for advanced users who will know what to do with it. Later I will guide novice users (who care about maximum security) to use this as well.

![image](https://cloud.githubusercontent.com/assets/6306961/21437438/a2686be6-c838-11e6-95c9-d90d0af8292c.png)

Later I will also think about other ways to protect the messages, such has scanning actual human fingerprints as an additional layer of security (for laptops that allow that).

**Comment by tomholub** [comment]
released early as version 2.6.2
