### ISSUE TITLE
Send email failure with no errors

### ISSUE THREAD

**Issue by exceptionwhisperer** [tomholub/cryptup-chrome#233]
When attaching a file to a intended secure email and the far end user recipient they do not have a PGP supported client the following is seen which is expected.
The smaller dialog box displays the details and issues related to the far end not have supported pgp clients is working as designed. It is suggestive and valid.

Can we add text to inform the user reads to tell them to remove the attachments for now as the email is not able to be sent.

The user also can check the box to keep the popup from showing up. 
What can happen is that me for example picks a user far end that does not have a detected PGP supported client. I see a popup I read it. The dialog box suggests I get them to  install one. OK I will work on that but I have already spent an hour typing so why cancel.
I choose to check the box to keep it the, popup  from showing up as its there and I don't want to see it since I keep clicking send and it keeps pop-ing  up over and over as it suggests a solution. There are gray items in the mail I can't send the email at all. 
Since the popup is removed  I then click send and the button changes to loading then no popup then back to normal a green button as if something happened but my mail dialog box is open still.
I repeat. Maybe popup a second box that says to send the email as the user might have spent a long time and its full of text, to remove the attachments after they clicked 5 or so times to keep re sending then nothing ever getst sent, This could cause closing the complete send box and giving up.
![image](https://cloud.githubusercontent.com/assets/24501419/21085722/20bcbb86-bfe3-11e6-8718-4438356fb5c9.png)

**Comment by tomholub** [comment]
That makes sense. I hope to switch the error notifications from a popup to an integrated message in the form itself. That way they can't stop them from showing.

I'll work on the wording, too, thanks!

**Comment by tomholub** [comment]
I have referenced this issue in #115 which covers it (more broadly). I have to move away from alert() as a way to provide error messages, and instead use messages rendered right in the UI. I'm closing this issue because it's covered in #115, and when #115 gets fixed, this will work properly as well. I've marked it as fairly high priority.
