### ISSUE TITLE
Click on the button Public key server in version 2.7.0 blank white screen is seen

### ISSUE THREAD

**Issue by exceptionwhisperer** [tomholub/cryptup-chrome#285]
On ubuntu and Windows , after upgrading to version 2.7.0 from 2.6.x now when user clicks on the button to see the info listed in Public key server. A dialog boxes open as expected, data was previously displayed.
Now after 2.7.0 is installed the box opens and the x in the upper right corner still shows, however not text is seen. 
This issue is displayed in ubuntu 16.04, and windows 10. Two differant gmail accounts used.

![screen blank for public key server](https://cloud.githubusercontent.com/assets/24501419/21511608/c556f32a-cc70-11e6-89f0-d12b57fc126b.jpg)
![debug info for blank screen](https://cloud.githubusercontent.com/assets/24501419/21511795/3853a920-cc73-11e6-9b2b-538f212ae9d8.png)

**Comment by tomholub** [comment]
I'll research this, thanks!

**Comment by tomholub** [comment]
**will be included in 2.8.0**
