### ISSUE TITLE
add missing licence statements

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#325]
- [x] `emailjs-stringencoding`is un-licenced as in https://github.com/inexorabletash/text-encoding/blob/master/LICENSE.md - still nice to include it
- [x] https://github.com/busterjs/formatio/blob/master/LICENSE to include in `lib/formatio.js`
- [x] `busterjs/samsam` BSD, need to include
- [x] fine uploader says commercial licence but link says mit. See in newer version matches licence
- [x] ericnorris/striptags - MIT, not included in file, but may not be needed. probably remove
- [x] zxcvbn - licence not included, it's MIT
- [x] open-sans.css missing a licence: it's Apache 2, add a link from https://fonts.google.com/specimen/Open+Sans
- [ ] check with mondo for his contributions

**Comment by tomholub** [comment]
@mondo989 Doing some cleanups, I will be adding attribution and licence statement next to your contributions, something like:
/*
Code in this file authored and contributed by: (c) 2016 Armando Flores, licensed under ____ available at: ________________
Later modified by: Tom James Holub
*/

Is it OK to licence it under MIT or BSD licence? It basically means anyone can do anything with the code. But I'll need your approval to do that.

**Comment by tomholub** [comment]
@mondo989 please confirm if it's ok to license your contributions under MIT. I'll then add a header to files that you authored or co-authored (eg settings) with your name & contact.

**Comment by mondo989** [comment]
Sorry @tomholub for the delay. Yes it's ok to license under MIT.

**Comment by tomholub** [comment]
kk sounds good!
