### ISSUE TITLE
Passphrase input is type text instead of password

### ISSUE THREAD

**Issue by digitalbreed** [tomholub/cryptup-chrome#362]
When I decide not to store my passphrase during setup and later want to decrypt a message, the popup uses a standard text input field instead of a password field.

<img width="653" alt="screen shot 2017-01-17 at 12 47 03" src="https://cloud.githubusercontent.com/assets/826466/22021343/04342d7c-dcbd-11e6-94b4-81be79452f09.png">

CryptUp 3.1.1
Chrome 55.0.2883.95
macOS Sierra 10.12.2 (16C67)

Not sure if this is a duplicate of #280 but that one sounds more like a convenience method to make it visible instead of the fact that it's not concealed at all.

**Comment by tomholub** [comment]
#280 will add a button to switch the field to a password field, `[my password    ]` vs `[***********     ]`. It's essentially a duplicate. I'll close the other one as this one is explained clearer.

It doesn't really matter which one is used as long as nobody is looking over your shoulder. I agree that having option to hide the password as you are typing it is a necessity.
