### ISSUE TITLE
requests for lookup seems to get doubled in compose window

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#503]
sometimes

**Comment by mondo989** [comment]
yep, this happens to me also quite periodically.

**Comment by tomholub** [comment]
Actually, what I was referring to is that the actual requests to the server get doubled.

What you had in mind is that visually, sometimes you'll see the recipients twice, or one red incomplete one and one that you wanted. (these issues may be related, now that I think of it)

Either way, the visually observable problem was fixed in #476, let me know if you still encounter it.
