### ISSUE TITLE
(Sometimes) Have to click chrome icon 2 times to open the container

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#508]
Probably around 20% of the time, when I click on the chrome icon, it opens like this...
When I click on it again, it opens correctly.

<img width="274" alt="screen shot 2017-02-19 at 12 50 24 pm" src="https://cloud.githubusercontent.com/assets/3431871/23105273/464c0ce4-f6a2-11e6-9727-acb1b4acf5f8.png">
Maybe it's just the extensions I use?

**Comment by tomholub** [comment]
will test

--
Tom

**Comment by tomholub** [comment]
I've seen this as well but not recently

**Comment by mondo989** [comment]
<img width="316" alt="screen shot 2017-03-19 at 8 16 04 pm" src="https://cloud.githubusercontent.com/assets/3431871/24087818/e9ecd762-0ce0-11e7-9132-b28724c01c7d.png">


I usually have to click two or three times... Maybe it's another gmail extension I'm using?

**Comment by tomholub** [comment]
Very interesting.. when this happens, try to right-click in the bubble that does show up and click on "inspect". See if there are any errors showing.

You can try to temporarily disable all other extensions in chrome and see if it helps.

**Comment by mondo989** [comment]
<img width="791" alt="screen shot 2017-03-19 at 10 32 10 pm" src="https://cloud.githubusercontent.com/assets/3431871/24089442/facaa560-0cf3-11e7-90f8-d30901d0c1eb.png">

Yeah, probably most definitely the extensions..

**Comment by tomholub** [comment]
Let me know if it's clear with other extension disabled, that's the key to figuring it out

**Comment by tomholub** [comment]
@mondo989 I may have found it. Let me know if you still experience this after you pull & reload.

**Comment by tomholub** [comment]
I'm closing this for now, if it's still an issue, let's reopen it
