### ISSUE TITLE
remaining things to do before replacing font-awesome

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#509]
- [x] `<i class="fa fa-repeat action_retry_pubkey_fetch"></i>`
- [x]  the huge green arrow when you install cryptup
- [x]  spinner
- [x]  the "expired-timer.svg" icon seems to take up super small part of the img, can you scale the vector up to take up the whole img, also it should be in white color
 - [x] `<i class="fa fa-download"></i>`

**Comment by tomholub** [comment]
I'll try to re-use the spinner you made earlier

**Comment by mondo989** [comment]
Hey @tomholub, is there a way to replicate the 'expired-timer' so I can see the problem?

I also have an updated icon for fa-repeat.

**Comment by tomholub** [comment]
Not easily, but if you just open `chrome-extension://nmelpmhpelannghfpkbmmpfggmildcmj/img/svgs/expired-timer.svg` in your browser (or equivalent if you have a different url), just make the circle icon expand from side to side to fill up the space

**Comment by tomholub** [comment]
@mondo989 actually, just load anyone in the compose box. Then replace the lock icon with the expired timer. Then you'll see

**Comment by tomholub** [comment]
also, pull pull pull :)

**Comment by mondo989** [comment]
Hahah, perfect idea actually! (Replacing it with an updated class)

And yep, I've been consistently having to stash changes with all your pushing lol

I should have the other remaining checks knocked out here in a little bit.

**Comment by tomholub** [comment]
I have all the spinners done!

**Comment by tomholub** [comment]
just saying :) I used your spinners from last time, made them white instead of green and put them inside the buttons.. I'm editting the svgs manually here lol. But the expired timer I wasn't sure how

**Comment by mondo989** [comment]
Yeah, I see them throughout, and they look niiiice!

**Comment by tomholub** [comment]
it looks damn nice

**Comment by mondo989** [comment]
<img width="423" alt="screen shot 2017-02-19 at 8 20 05 pm" src="https://cloud.githubusercontent.com/assets/3431871/23109685/e27fe688-f6e0-11e6-8063-b5e8762f8a1d.png">

I increased the stroke a bit on the svg, and added some css, to update the style a bit, but it wouldn't render when I would update it from the browser.

**Comment by tomholub** [comment]
Yes we can go a bit thicker

**Comment by mondo989** [comment]
<img width="660" alt="screen shot 2017-02-19 at 8 30 40 pm" src="https://cloud.githubusercontent.com/assets/3431871/23109869/57723bf2-f6e2-11e6-9235-479dbb19042c.png">
This is it, with the CSS rendered. Which it should when called in properly

**Comment by tomholub** [comment]
kk it looks good

**Comment by mondo989** [comment]
<img width="563" alt="screen shot 2017-02-19 at 8 32 55 pm" src="https://cloud.githubusercontent.com/assets/3431871/23109904/a66549ac-f6e2-11e6-905c-d62568cb9819.png">


Also, on the retry 'span' which color will it be? 
I think it may have changed to gray now?

**Comment by mondo989** [comment]
If it's gray, I can just update the SVG to white, and we should be ok.

**Comment by mondo989** [comment]
I would like to modify the spinner just a tad bit, but it keeps disappearing on me :/ lol

**Comment by tomholub** [comment]
you can just replace something else with the spinner

Actually when the "retry" icon shows, it will be on a white background.

Disable your wifi, try to look someone up that you didn't write before, you'll see

**Comment by mondo989** [comment]
Ok so having the retry icon as it is, probably shall work then.

Also, Thanks, I knew you'd have the answer for the spinner lol

**Comment by mondo989** [comment]
@tomholub it doesn't just hang on spinner, it shows me the retry icon. (Which is nice)
I'll just find a way to insert the spinner in

**Comment by mondo989** [comment]
@tomholub I'll let you confirm and close it out. 

Let me know if you seen anything that needs some love.

**Comment by tomholub** [comment]
great let me see

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
It's all great. I'll just adjust the size of attachment download spinner

**Comment by tomholub** [comment]
I declare this issue CLOSED

**Comment by tomholub** [comment]
Thanks @mondo989 !

**Comment by tomholub** [comment]
found a minor issue

![2017-02-19-193252_1115x1056_scrot](https://cloud.githubusercontent.com/assets/6306961/23110977/3eae7d04-f6da-11e6-8561-a6c75b4b6152.png)

I'll be off for 20 min

**Comment by mondo989** [comment]
Whoa, when you click the "Cryptup icon in chrome browser"?

**Comment by tomholub** [comment]
yeah

**Comment by tomholub** [comment]
somehow, I had it zoomed by the browser. Which is weird because it won't show you that it's zoomed, and it requires that you open the popup manually in a new tab and zoom it back.

I will just prevent browser zooming in css.
