### ISSUE TITLE
visual design: attachments (send + receive)

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#51]
I just added a way to send encrypted attachments (for now only text files) and also receive them.

I used a very basic design I'll show in the screenshots, and a better design would be awesome :)

**Sending attachments**
 - attaching: it should show a nice list of attached files similar to normal gmail, but maybe green?
 - it should show that attachments will be encrypted, (for now with a green lock icon next to each?), later with CryptUP icon (once we have it)
 - I guess the "cancel" button should just be a simple X icon
 - the "edit" button is bogus and will be removed later
![2016-03-09-110642_624x830_scrot](https://cloud.githubusercontent.com/assets/6306961/13624364/57eb7afa-e5e8-11e5-8b74-47d14f6af3a9.png)

**Receiving attachments**
 - each attachment file box that is encrypted gets replaced with a little iframe
 - you can style anything inside the iframe
 - it should feel similar to normal gmail attachments, but show clearly (also in text) that the files are encrypted
 - for now will also use the green lock icon, but I hope in future to replace it with CryptUP icon

![2016-03-09-110909_851x830_scrot](https://cloud.githubusercontent.com/assets/6306961/13624365/5e02c79a-e5e8-11e5-9e77-a3d7fa7ad6ed.png)

Please post screenshots/photoshop deisgns here first (as a reply) and then we put it into code later

thanks!

**Comment by mondo989** [comment]
For Sending attachments:

I agree we should somewhat close to Gmail, but still just a little different.
We can use the x and put the lock icon in front as they are effective.
The lock will be nice reassurance for the user to know that their attachment is encrypted.
The attach icon is a little larger.

<img width="936" alt="screen shot 2016-03-08 at 10 07 11 pm" src="https://cloud.githubusercontent.com/assets/3431871/13626798/212fc82c-e57a-11e5-8859-2651ffbbc20e.png">

**Comment by tomholub** [comment]
**sending** - I like it

**receiving** -  consider this scenario - some files might be encrypted and some not, so it might look like this:
![image](https://cloud.githubusercontent.com/assets/6306961/13627770/d620e224-e607-11e5-82ef-ca3c7197aa1c.png)

So I think it would make sense in this case to make it a bit more consistent with gmail. Maybe throw away the "text/plain" and then have the name of the file in a footer similar as the other one. Maybe the thing on the bottom right should be green? Let me know

**Comment by mondo989** [comment]
For receiving, I agree.

Can we change the properties in the bottom right corner? 

<img width="861" alt="screen shot 2016-03-09 at 12 07 16 am" src="https://cloud.githubusercontent.com/assets/3431871/13628972/10b93724-e58b-11e5-8b1c-00d04ed2af4a.png">

**Comment by tomholub** [comment]
Looks great. Yes whatever you need to do :) you might need to draw your own
assets for the little guy in the corner. I just copied it from gmail, but
badly.

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
To implement this, you can unlink `<link rel="stylesheet" href="/lib/fine_uploader/fine-uploader-new.css" />` and add the necessary styles into `gmail_elements.css`.  For receiving, right now that is also at the end of that file, the lines `body.attachment ...`

**Comment by mondo989** [comment]
Here's how the attached text files look right now.
- I commented out the edit button. (Gmail doesn't use an edit icon/button)
- I put an icon inside of the cancel button, which I made css to remove the button properties.

<img width="575" alt="screen shot 2016-03-11 at 1 27 34 am" src="https://cloud.githubusercontent.com/assets/3431871/13698684/882e8584-e72a-11e5-8a9e-1427933e1dfd.png">
<img width="574" alt="screen shot 2016-03-11 at 1 25 31 am" src="https://cloud.githubusercontent.com/assets/3431871/13698685/882ec26a-e72a-11e5-8e12-e645571c2fd2.png">

**Comment by mondo989** [comment]
Maybe we can have the file size as how gmail has it?
<img width="470" alt="screen shot 2016-03-11 at 1 46 32 am" src="https://cloud.githubusercontent.com/assets/3431871/13698805/3e2a24ba-e72b-11e5-8377-678e79d3bcbf.png">

**Comment by mondo989** [comment]
Current extra feature.... 
   Whenever the user clicks on the anything that's not the X, the element becomes content editable and the x goes a little wild. 

<img width="567" alt="screen shot 2016-03-11 at 2 07 35 am" src="https://cloud.githubusercontent.com/assets/3431871/13699293/4bc1e70e-e72e-11e5-8448-647be06596eb.png">


Sorry for all the spam

**Comment by tomholub** [comment]
I'll disable the click, np. And definitely, let's add size, just say (1K)
everywhere and I'll fix it after. Looks good!

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Cool!

I've pushed updates...

One thing to note is that after 3 text files the new ones get pushed below the email's body input, it basically just disappears...  Notice on the third attached †ext file, it kind of starts to fall under... 
<img width="566" alt="screen shot 2016-03-11 at 4 36 58 pm" src="https://cloud.githubusercontent.com/assets/3431871/13719242/9a19b872-e7a7-11e5-8823-d2b10766cb05.png">

**Comment by tomholub** [comment]
Yes I was thinking about this.. I will fix that for now, the danger is that
these files will stack all the way up and then obstruct the written text. I
have an idea how to fix it, that we can explore later, for now I will allow
10 attachments per email or so.

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
not sure if I broke it or not, but it's showing like this now:

![2016-03-12-110727_688x715_scrot](https://cloud.githubusercontent.com/assets/6306961/13720405/c6aac6b0-e842-11e5-92a4-0863740e3a52.png)

**Comment by tomholub** [comment]
correction, the `X` got fixed somehow. Also fixed more than 3 attachments.

The only thing left for now are the little file iframes, thanks!

**Comment by mondo989** [comment]
Glad it fixed.
The scroll bar is a bit ugly on yours, so I added some css to hopefully hide the scrollbar.
It still goes to content editable on click.

**Comment by tomholub** [comment]
Good work!
