### ISSUE TITLE
When typing in multiple email address, the auto-suggestions gets in the way.

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#510]
<img width="1020" alt="screen shot 2017-02-19 at 8 42 04 pm" src="https://cloud.githubusercontent.com/assets/3431871/23110131/6fe0f398-f6e4-11e6-8ab1-f6c052dbe882.png">

**Comment by tomholub** [comment]
good find, I was thinking to test it, then I forgot. I think I used to have
this working.

--
Tom

**Comment by tomholub** [comment]
should be better now
