### ISSUE TITLE
Clicking the "Secure Compose" button on Gmail, opens the cryptup 'modal,' but the input is not "in focus" by default.

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#512]
I have to click again, on the recipients input and type the names I am sending it too.
It's this way from settings as well as in gmail.

Gmail - clicking compose opens the compose window, 'in focus'

(Not too major but could improve the experience a bit)

**Comment by tomholub** [comment]
good find, try again now

**Comment by mondo989** [comment]
This makes me happy :)
