### ISSUE TITLE
random logo ideas

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#52]
I'll be posting some random logo ideas here. Pencil/pen/photoshop/other sketches like that are fine, it's just ideas :)

Too generic:
![image](https://cloud.githubusercontent.com/assets/6306961/13624489/8a9d277c-e5e9-11e5-965c-aca59618392b.png)

I kind of like this (as a brainstorming idea)
![image](https://cloud.githubusercontent.com/assets/6306961/13624620/d65d01c2-e5ea-11e5-994a-d9beb8f95d31.png)

Also not bad (as a brainstorming idea)
![image](https://cloud.githubusercontent.com/assets/6306961/13624623/da28acd4-e5ea-11e5-9139-7d4c685a3982.png)

All of these are random pics from google, ours needs to be more differentiated.

**Comment by mondo989** [comment]
Just a few crappy photoshop versions.. I have some drawing i'll upload too
<img width="590" alt="screen shot 2016-03-09 at 1 35 26 pm" src="https://cloud.githubusercontent.com/assets/3431871/13651370/e98de6d8-e5fb-11e5-8b3d-348cd1656103.png">
<img width="632" alt="screen shot 2016-03-09 at 1 34 38 pm" src="https://cloud.githubusercontent.com/assets/3431871/13651373/e9906f52-e5fb-11e5-88af-226765303671.png">
<img width="548" alt="screen shot 2016-03-09 at 1 33 37 pm" src="https://cloud.githubusercontent.com/assets/3431871/13651372/e9905f62-e5fb-11e5-93eb-6b804da41641.png">
<img width="491" alt="screen shot 2016-03-09 at 1 11 39 pm" src="https://cloud.githubusercontent.com/assets/3431871/13651371/e98fdf6a-e5fb-11e5-9ce3-5db919dd81b5.png">
<img width="441" alt="screen shot 2016-03-09 at 1 08 00 pm" src="https://cloud.githubusercontent.com/assets/3431871/13651374/e990e216-e5fb-11e5-8f82-ca60bd051ada.png">

**Comment by tomholub** [comment]
For now crappy versions are perfect for brainstorming, thanks!

**Comment by mondo989** [comment]
Maybe one that isn't flat and combines mail and lock.
I think this one is possibly a little better than meh.

![img_2309](https://cloud.githubusercontent.com/assets/3431871/13654912/5de2ae74-e610-11e5-948c-112173276445.jpeg)

**Comment by tomholub** [comment]
Interesting idea.. not bad!

**Comment by tomholub** [comment]
**more randomness**

That stuff is mine
![image](https://cloud.githubusercontent.com/assets/6306961/13726387/3366c408-e900-11e5-9c41-02a338fe4aab.png)

In Encryption We Trust
![image](https://cloud.githubusercontent.com/assets/6306961/13726438/d838c656-e901-11e5-9b1b-a7b282679c83.png)

I hold my email
![image](https://cloud.githubusercontent.com/assets/6306961/13726459/2c09c7f2-e903-11e5-8b98-feb97d840f2d.png)

GMail Key
![image](https://cloud.githubusercontent.com/assets/6306961/13726561/b162fd7a-e907-11e5-9fb9-4dcfcd1b530c.png)

**Comment by chejazi** [comment]
I think shields convey a positive sense of protection. Something like this maybe:

![shield](https://cloud.githubusercontent.com/assets/2603535/13768297/90da03fc-ea31-11e5-824c-8f127f660649.png)

**Comment by tomholub** [comment]
I agree, I just worry that shields and locks are too generic to make a recognizable brand icon out of it :( That's why I kind of liked armando's https://github.com/tomholub/cryptup-chrome/issues/52#issuecomment-194577732 - it's more unusual. But still missing something to make it really unique

**Comment by tomholub** [comment]
I think we could make it unique with something unrelated as well, as long as it shows trust/security/protection somehow. A mascot animal like linux penguin or badger of gethoneybadger.

Maybe an owl will save the day? lol

![image](https://cloud.githubusercontent.com/assets/6306961/13769654/53e87fec-eabc-11e5-8a26-12f209c478a6.png)

just random

**Comment by mondo989** [comment]
Yeah I really like the creativity! 
I wonder if alone it is a bit too generic and the user won't be able to tell that this is for encrypted email. 

Ideally the user could be able to see the cryptup button next to the generic compose button and know that this is how they send encrypted emails.

**Comment by tomholub** [comment]
Depends on the branding. If the icon is used everywhere (CryptUP page, plugin page, browser action button, settings, and inside gmail window, and attachments), then it could be almost anything, as long as it's unique and shows a key/lock/shield/safe kind of thing

**Comment by tomholub** [comment]
I think, with enough random ideas, we'll eventually find out which direction to take it

**Comment by tomholub** [comment]
I like this concept for a logo (but someone has already thought of it! :) )

![image](https://cloud.githubusercontent.com/assets/6306961/13773602/0dea9304-ead5-11e5-8405-aab89f9fa5bb.png)

**Comment by tomholub** [comment]
Building on that concept + armando's idea:

![image](https://cloud.githubusercontent.com/assets/6306961/13774932/9a72f0da-eadc-11e5-892e-e01ce374f019.png)  

![image](https://cloud.githubusercontent.com/assets/6306961/13775118/c4c8fc02-eadd-11e5-89e8-7571d721fef3.png)

![image](https://cloud.githubusercontent.com/assets/6306961/13775014/2be5602a-eadd-11e5-92af-5e92d0747578.png)

**Comment by tomholub** [comment]
@mondo989 let me know if you have any ideas, I'm compelled to go with something like

**Comment by mondo989** [comment]
I've been playing around with a few, It's a bit difficult to make it look like an email lock hybrid without having it look like a breifcase lol.

See this one:
<img width="626" alt="screen shot 2016-03-15 at 2 25 06 am" src="https://cloud.githubusercontent.com/assets/3431871/14002121/00471942-f107-11e5-83a6-46e73120be2b.png">

A
![test2](https://cloud.githubusercontent.com/assets/3431871/14002136/194b4788-f107-11e5-9e7c-5eef01fa184a.png)
![test1](https://cloud.githubusercontent.com/assets/3431871/14002135/19496c06-f107-11e5-8cd1-11a336afe43a.png)

nother potiental problem might be it's a bit more rectangular.

Maybe it's a bit cliche, but what if we think about something like this, an email, with the green with a lock overlayed

![test1](https://cloud.githubusercontent.com/assets/3431871/14001923/cf22466c-f105-11e5-9e2e-7a3d00a3fe2c.png)

**Comment by mondo989** [comment]
This is what it could potentially look like.
![shot](https://cloud.githubusercontent.com/assets/3431871/14002494/a04f69d8-f109-11e5-9cf7-c9f56a8488bf.png)

**Comment by tomholub** [comment]
getting better! the first one is the best, because it will probably look the best when scaled down.

And you're right, I was definitely struggling with the briefcase haha.

We just need to design it in a way that small would still look good, and fit into a square nicely :) Added a keyhole, and made it a bit more square by flattening the top (just experiments)

![image](https://cloud.githubusercontent.com/assets/6306961/14009366/24c1c7b2-f1c6-11e5-8642-7d5bb75ae87b.png) ![image](https://cloud.githubusercontent.com/assets/6306961/14009408/8e5f6710-f1c6-11e5-8273-f446103d0645.png)

![image](https://cloud.githubusercontent.com/assets/6306961/14009375/38925036-f1c6-11e5-9025-381afa75a399.png) ![image](https://cloud.githubusercontent.com/assets/6306961/14009411/96584a54-f1c6-11e5-8bda-f0966ca08150.png)

![image](https://cloud.githubusercontent.com/assets/6306961/14009382/57382510-f1c6-11e5-9490-c8d49dd5552b.png) ![image](https://cloud.githubusercontent.com/assets/6306961/14009419/a259d6d8-f1c6-11e5-99cf-4386611d973f.png)

Would love to see more experiments like that

**Comment by mondo989** [comment]
Playing around a bit more

![testinginte](https://cloud.githubusercontent.com/assets/3431871/14012209/800f6292-f161-11e5-9ba9-64d28614d056.png)
![test-teste-tes](https://cloud.githubusercontent.com/assets/3431871/14012210/800fe992-f161-11e5-8365-2abb53f721f7.png)

, didn't put too much emphaiss on the stroke.

**Comment by tomholub** [comment]
Can the logo be simplified? Try to design it to the size of the button. Then later we can try to scale it up. It should end up being simpler, because of the small space.

**Comment by tomholub** [comment]
how about something like this? Some kind of simple logo that utilizes the letter "C" or "U" or maybe "UP"

![image](https://cloud.githubusercontent.com/assets/6306961/14069256/1f037792-f4ca-11e5-9231-fcbca09cef36.png)

**Comment by tomholub** [comment]
Actually, might as well. Haha so far I prefer this the most

![image](https://cloud.githubusercontent.com/assets/6306961/14070014/abdbc508-f4d3-11e5-8c58-b531d91f298a.png)

![image](https://cloud.githubusercontent.com/assets/6306961/14070006/9575ca84-f4d3-11e5-861b-95ac5e8ce3e4.png)

![image](https://cloud.githubusercontent.com/assets/6306961/14070004/8dc16be0-f4d3-11e5-9371-2bf1965c62cb.png)

**Comment by tomholub** [comment]
The browser icon is 19x19

![image](https://cloud.githubusercontent.com/assets/6306961/14070173/ad175520-f4d5-11e5-9a51-39ee1d3e5d3b.png)

**Comment by tomholub** [comment]
![image](https://cloud.githubusercontent.com/assets/6306961/14070222/6cc784d0-f4d6-11e5-8589-3b5cdeda3fe7.png)

**Comment by mondo989** [comment]
Sure, it works.

On Sunday, March 27, 2016, Tom James Holub <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/6306961/14070222/6cc784d0-f4d6-11e5-8589-3b5cdeda3fe7.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tomholub/cryptup-chrome/issues/52#issuecomment-202215714>
>


-- 
Armando Flores
Armando.sx

**Comment by tomholub** [comment]
have to resize / optimize some of the logos
