### ISSUE TITLE
'Feedback link' is on settings twice, can we use icon instead of 'need help' link?

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#521]
<img width="962" alt="screen shot 2017-02-20 at 1 04 42 pm" src="https://cloud.githubusercontent.com/assets/3431871/23141881/89c968cc-f77e-11e6-8e31-f1ca19c86146.png">

Was thinking that we can change the link to (question) icon and put subscription status on lower left corner. 

<img width="993" alt="screen shot 2017-02-20 at 12 50 57 pm" src="https://cloud.githubusercontent.com/assets/3431871/23141954/f5086304-f77e-11e6-911f-c7ff333f0b5f.png">

**Comment by tomholub** [comment]
I actually want to keep it this way for now, I want to make it as easy and clear as possible for people to write me. There's space on the settings page, anyway. Once I start getting overwhelmed with messages, we may consider to obscure these links a tad bit :) or just have one of them. But I'm nowhere near getting overwhelmed. I'll close this for now.
