### ISSUE TITLE
Adjust spacing on Settings Icons

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#522]
The margin on the settings icons were thrown off a bit. 

<img width="1277" alt="screen shot 2017-02-21 at 8 11 25 am" src="https://cloud.githubusercontent.com/assets/3431871/23168317/5fbd16ac-f80d-11e6-8734-d8c080ae94e6.png">

**Comment by tomholub** [comment]
we fixed this recently by getting rid of `display: initial`
