### ISSUE TITLE
visual design: settings: back + email

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#53]
The following screens are missing two things:
 - a back button (also more screens than that)
 - showing which email account is it about (right now we show it in the `<h1>` which is shitty)

Where would you ideally put the back button? Would it be a link `<a>back</a>`, or icon? Also, how would you visually show which email account is it about instead of mentioning it in the title?

If you have any visual ideas, please post them here :)

![2016-03-09-114605_851x830_scrot](https://cloud.githubusercontent.com/assets/6306961/13624831/8bc79a80-e5ec-11e5-9a48-b6148a33436e.png)

![2016-03-09-114730_960x1056_scrot](https://cloud.githubusercontent.com/assets/6306961/13624849/bdcaab94-e5ec-11e5-91cf-2662478fd8bb.png)

**Comment by mondo989** [comment]
Maybe we bring the font size down some and put the back arrow on the same row.

The back arrow will be an icon element nested inside of a anchor tag.

<img width="1292" alt="screen shot 2016-03-09 at 12 25 10 am" src="https://cloud.githubusercontent.com/assets/3431871/13629366/87ad0b4c-e58d-11e5-8dac-3526d45a6f4a.png">

**Comment by mondo989** [comment]
We would definitely want to make the font color on h1's darker
<img width="831" alt="screen shot 2016-03-09 at 12 46 25 am" src="https://cloud.githubusercontent.com/assets/3431871/13629825/7306d9b8-e590-11e5-992f-829838ba78f7.png">

**Comment by tomholub** [comment]
Not bad. Maybe the arrow would be a little more subtle (try different
shapes).

Do you think we should keep the emails in the H1? Or move it somewhere?

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Yeah totally agree, not a fan of the arrow style.
Think of it as a placeholder until we decide to go with this layout style or something else.

I think having the email address as a h1 adds very small value, given the variation of email characters.

it would probably be better to have the address in the upper right hand corner with an settings icon(or some other icons) next to their email address, as people are already familiar with this layout style. 

(quick draft, copy and icons, and color would be better)
<img width="1261" alt="screen shot 2016-03-10 at 11 36 24 pm" src="https://cloud.githubusercontent.com/assets/3431871/13696133/36619040-e719-11e5-8121-07f2488ceeba.png">

**Comment by tomholub** [comment]
I like this a lot! Next to that email, I'd probably put generic person
silhouette and I'll pull their gmail pic from the api to show there.

Also, maybe it would make sense to put a header across the whole thing,
kind of like this:

[image: Inline image 2]

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
![image](https://cloud.githubusercontent.com/assets/6306961/13701641/3e37d3aa-e7c4-11e5-9498-54c46f520cdd.png)

**Comment by mondo989** [comment]
Ah, having their gmail pic sounds great!

Also, can't see the attached image

**Comment by mondo989** [comment]
I also think it makes more sense to have the back arrow inside of the containing row.

If we put it to the in the upper left hand corner, it's almost like another back button that's pretty close to the actual back button. 

<img width="634" alt="screen shot 2016-03-11 at 11 13 59 am" src="https://cloud.githubusercontent.com/assets/3431871/13712796/7902ea6e-e77a-11e5-9f34-7ac3ad769d15.png">


(An exaggeration)

**Comment by tomholub** [comment]
got it, kk, sounds good!

**Comment by mondo989** [comment]
Would you like me to implement it?

**Comment by tomholub** [comment]
absolutely :)

**Comment by mondo989** [comment]
A screenshot of what I pushed.

<img width="1583" alt="screen shot 2016-03-14 at 12 57 48 pm" src="https://cloud.githubusercontent.com/assets/3431871/13758045/8e6ca1d0-e9e4-11e5-8dd5-3dcf283f54ff.png">

I added in Open Sans font and a subtle animation to the arrow, to show that it is something that you can interact with.

Right now everything is static, the arrow is an <i> tag with a cursor:pointer to simulate anchor tag

**Comment by tomholub** [comment]
awesome, can you put it on all settings pages? They all share the same CSS
(but different htmls). And I'll go ahead and make it dynamic :)

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
I see what you mean here...

**Comment by mondo989** [comment]
Just pushed, let me know if you notice any special features.

**Comment by tomholub** [comment]
Thanks! Had to add missing animate/font styles to all pages, then it worked. Also for now commented out the photo and added icon instead, will have to add profile pics later when I learn how.

**Comment by mondo989** [comment]
Ah sorry about that, I'll pay closer attention next time.

**Comment by tomholub** [comment]
No worries, thanks for help, it's looking good!
