### ISSUE TITLE
show who uses encryption in standard compose

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#554]

**Comment by mondo989** [comment]
Just crawling through labels now... 
So if I am using 'Regular Gmail' with CryptUp installed, it will show that user can receive encrypted emails?

**Comment by tomholub** [comment]
Yeah that's what this issue is for. That way you may interact with the
plugin more because you may discover someone uses encryption who you didn't
know they do.

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Sounds like a cool way to learn who sends/receives encrypted emails.
