### ISSUE TITLE
links in pgp_block should be clickable

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#570]

**Comment by tomholub** [comment]
another request https://mail.google.com/mail/u/1/#inbox/15ac3ed8a850422f

at the very least, can recognize links and convert them to clickable
better would be to somehow parse the original ones and preserve them

**Comment by mondo989** [comment]
Not quite sure what this means...

**Comment by mondo989** [comment]
<img width="318" alt="screen shot 2017-03-14 at 9 53 00 pm" src="https://cloud.githubusercontent.com/assets/3431871/23934168/a4eb2ddc-0900-11e7-8e7c-eb763dc434f2.png">


Are they clicking on these guys?

**Comment by tomholub** [comment]
When I send you a link inside encrypted message - you can't click on it :)

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Hahaha! Yes, I would definitely complain about that too
