### ISSUE TITLE
reply box can double up - try to prevent it

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#608]
![2017-03-13-071421_1920x1056_scrot](https://cloud.githubusercontent.com/assets/6306961/23858163/ca774800-07bc-11e7-8e3c-0082895af367.png)

**Comment by tomholub** [comment]
when it happens, it will happen in every convo, until it doesn't anymore. couldn't debug because it was on prod

**Comment by mondo989** [comment]
I recall this happening to me a long while back... Not so much anymore...
