### ISSUE TITLE
Footer breaks when browser is smaller than 766px.

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#621]
<img width="771" alt="screen shot 2017-03-14 at 9 31 29 pm" src="https://cloud.githubusercontent.com/assets/3431871/23933740/c2654aee-08fd-11e7-867c-525bb36cf108.png">

**Comment by tomholub** [comment]
Should be ok though, right? Do any laptops still have that small resolution
today? :)

--
Tom

**Comment by mondo989** [comment]
Hahaha yes definitely, for sure. 
I was going to write low priority, it just bugs me a little bit. lol

**Comment by tomholub** [comment]
haha np it can definitely be fixed

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
I'll knock it out real quick.
