### ISSUE TITLE
Long Passphrases run into the hide button

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#622]
<img width="427" alt="screen shot 2017-03-13 at 9 38 51 pm" src="https://cloud.githubusercontent.com/assets/3431871/23933775/00091768-08fe-11e7-9e3f-c1072c0ac83d.png">

**Comment by tomholub** [comment]
interesting find, not ideal

--
Tom

**Comment by mondo989** [comment]
Yeah, I was changing my passphrase to a longer one, and that happened.

**Comment by mondo989** [comment]
I updated it in 3 places... 
if you want to test, confirm, close.

<img width="680" alt="screen shot 2017-03-14 at 10 58 51 pm" src="https://cloud.githubusercontent.com/assets/3431871/23935582/d844af4c-0909-11e7-85bd-b40158ccffca.png">

**Comment by tomholub** [comment]
perfect, I applied it to all of them
