### ISSUE TITLE
When refreshing (quickly) in settings, I see the setup block inside of the settings block.

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#624]
Trying to take a screenshot and wondering... Does this happen to you @tomholub?

**Comment by tomholub** [comment]
yeah it shows for a split second, I was going to fix it later

because all blocks are visible by default, and only after the code figures out which one to show does it hide the other ones

it should be the other way

**Comment by mondo989** [comment]
Got ya... 
I was also considering another possible 'temporary' fix is that we can put delays on the transition of the block. And by default make it wait a (half or less) of a second before doing anything.
Can look into it if you'd like..

**Comment by mondo989** [comment]
I have it about all figured out, just need to test it in the initial signup ...

**Comment by tomholub** [comment]
you can reset the account in additional settings -> experimental -> reset
account

it will be fine if you remember pass phrase

you can check passphrase in security box before you do this

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
@tomholub I deleted and reinstalled... 
I've both settings blocks a .25s delay before their transition appears... 

Let me know if it works for you

**Comment by mondo989** [comment]
Also, that's good to know 👍

**Comment by tomholub** [comment]
looks great now! that's an awesome fix
