### ISSUE TITLE
use proper /upload API for attachments

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#63]
otherwise uploading is very slow

**Comment by mondo989** [comment]
I saw that you added in the drag and drop, very cool. 

Maybe there should show the use some sort of prompt as they are dragging files into the email field.

**Comment by tomholub** [comment]
Kind of, I plan to add D&D later for the whole compose window. For now it's a "hidden feature" but you can definitely make some sort of prompt that will show up when you hover with a file, like gmail, and then make the prompt `visibility: hidden`, so that I can unhide it when file is hovering. I think it should cover the whole text area similar to gmail?

**Comment by mondo989** [comment]
Ok cool, I found a hidden feature! 
We can wait until another iteration, but yeah it should definitely cover the whole text area. 
When we are ready for it, just assign it to me as a different issue.

**Comment by tomholub** [comment]
kk
