### ISSUE TITLE
what to do when user reinstalls app and forgot password

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#79]
right now this leaves the user stuck

**Comment by mondo989** [comment]
Yeah this happened to me too, I just created a new one.

Very cliche, but maybe allow the user to answer a security question and that will send them the password to their account?

**Comment by tomholub** [comment]
Actually, their email is completely lost in that case, we cannot hold anything for them, for security reasons. 

But once in a while I will prompt them to double check they still know the password so it should happen less.

But once it does happen, I basically need to tell them they can't open anything until they remember, and make a new key for new email.
