### ISSUE TITLE
initial setup options: better design

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#84]
to think through more

**Comment by mondo989** [comment]
Maybe on the onboarding we provide them with two options:

![ob2](https://cloud.githubusercontent.com/assets/3431871/14091062/c91cd49e-f4f2-11e5-874a-96ea1cb609df.png)
Rough, but maybe something along these lines?

**Comment by tomholub** [comment]
Yes something like that is definitely a way to go, I have to think more
about the wording.

Maybe the first icon should be showing a stopwatch, or clock dial etc
showing it's fast

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Sure, I can add in/play around with icons. 
Let me know an update on the wording.

**Comment by tomholub** [comment]
The words will be as now. I would use a stopwatch? to show the quick one. Not sure what to use for the advanced. Lock would probably do, or just show icon with something complicated, like a list of checkboxes. Just brainstorming.

![2016-04-14-234526_865x672_scrot](https://cloud.githubusercontent.com/assets/6306961/14534286/02666b2e-029b-11e6-9d31-40cd2fa964d3.png)

**Comment by mondo989** [comment]
Kind of placeholder, still experimenting with the icon and styling to the right.
The green cog and gray border are clashing a bit... 

<img width="951" alt="screen shot 2016-04-20 at 1 33 18 am" src="https://cloud.githubusercontent.com/assets/3431871/14664323/fb0da71a-0697-11e6-9db8-95d2148834ca.png">

**Comment by tomholub** [comment]
Great start. Maybe make stopwatch bigger, the size of the gray circle, and the cogs a bit bigger. And get rid of gray circles, see how it comes out

**Comment by mondo989** [comment]
<img width="1074" alt="screen shot 2016-05-23 at 10 48 21 am" src="https://cloud.githubusercontent.com/assets/3431871/15479218/efd511fc-20d3-11e6-9a28-2a8fa3639513.png">


Made larger and removed circles

**Comment by tomholub** [comment]
I love it

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
This too? :)

**Comment by tomholub** [comment]
yup :)
