### ISSUE TITLE
make receivers on multiple lines look/behave better

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#95]
![2016-03-23-001451_668x719_scrot](https://cloud.githubusercontent.com/assets/6306961/13958761/4bf6787c-f08c-11e5-9459-7234ac754d0a.png)

**Comment by mondo989** [comment]
Oh hi there :)

So I really like the idea of spinner per each email address.

How do you feel about them having a little span with a lock/unlock per each one. looking something like this?

<img width="780" alt="screen shot 2016-03-22 at 6 21 50 pm" src="https://cloud.githubusercontent.com/assets/3431871/13971210/3e4c3fc0-f05c-11e5-86a4-66fd05992249.png">

**Comment by tomholub** [comment]
I was thinking about it! But then, even the orange guy will get the email encrypted (with a question). So I'm not 100% sure how to approach it. Not sure how to indicate that a certain person will have to unlock it with an answer.

**Comment by mondo989** [comment]
Got ya. Good point.

Ok so what about if per each address, we use an icon. 

If it requires a question, we put a question icon, and show the same question icon larger with the prompt below. 

If it's good to go they get the green lock icon.

<img width="909" alt="screen shot 2016-03-23 at 1 45 22 pm" src="https://cloud.githubusercontent.com/assets/3431871/14000250/a0a7dbb0-f0fd-11e5-99e9-cf0da66471a3.png">

**Comment by tomholub** [comment]
not bad! Is there other icon we could use? Question mark to me seems to
imply that we don't know if it's secure or not. Maybe just a lock in gray
background, and the same on the bottom where it is explained?

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
What do you think about a lock with a key?

<img width="933" alt="screen shot 2016-03-25 at 12 18 01 pm" src="https://cloud.githubusercontent.com/assets/3431871/14051946/b17d6216-f283-11e5-8547-b23cd5ad242c.png">

**Comment by tomholub** [comment]
Haha, yes, can be. I like it

**Comment by mondo989** [comment]
Screenshot to #95

![Uploading Screen Shot 2016-03-26 at 3.31.02 AM.png…]()

**Comment by tomholub** [comment]
closing in favor of #99
