### ISSUE TITLE
managing/removing secondary send-from addresses

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#96]
Right now, it will pull many addresses that were used in the past, many of which may not be used anymore.
- only look 1 year in the past when pulling
- allow to hide unwanted ones

**Comment by 4cm4k1** [comment]
Hi! I just found CryptUp, and I just want to say this is really, _really_ well done. I’ve arduously taught myself how to use GnuPG/PGP with my YubiKey, so it’s really something to see a product that I feel like I could probably show my mom how to use.

*However,* during signup, it seems many of my _really_ old “send as” aliases (that don’t even exist anymore?) got picked up. How does CryptUp query the Gmail API to retrieve them? I assume maybe via past email threads. I’ve been looking through the code for a bit, but haven’t found it yet. If there’s any way I can help to make removal happen, I’d be happy to! This is really great!

**Comment by tomholub** [comment]
Thanks! You're right, it's looking at past threads and extracting send-from addresses. Gmail doesn't have any API for this that I know of.

This is not hard create an interface for this but I gave it a low priority, as people can generally live with a few extra addresses, while other issues may cause them to not be able to use the plugin at all.

**Comment by tomholub** [comment]
- [ ] remove object extensions
 - [ ] rename buttons

**Comment by tomholub** [comment]
@4cm4k1 It was a good idea to put it on the Servers page. I was delaying this mostly because I didn't want to make a new interface and was not sure where to put it. This is a good place for it. Thanks!

**Comment by 4cm4k1** [comment]
Thanks @tomholub! I thought I would try to help out simply because this is cool, and I didn't want to stare at all my old aliases, and I saw it on your roadmap. 😊

**Comment by tomholub** [comment]
If you see any other room for improvement, let me know. Also a review would be great! :)
https://chrome.google.com/webstore/detail/cryptup-encrypt-gmail-wit/bnjglocicdkmhmoohhfkfkbbkejdhdgc/reviews
