### ISSUE TITLE
Too many recipients break recipient's <td>

### ISSUE THREAD

**Issue by mondo989** [tomholub/cryptup-chrome#99]
<img width="551" alt="screen shot 2016-03-26 at 3 33 34 am" src="https://cloud.githubusercontent.com/assets/3431871/14059607/8bc30d48-f303-11e5-8bcf-a48704235268.png">

**Comment by tomholub** [comment]
single line ok now (there is dynamic input[text] width resizing)

![2016-03-27-190614_787x866_scrot](https://cloud.githubusercontent.com/assets/6306961/14065119/55d94ee8-f44f-11e5-821a-dbba49bfa4fc.png)

**Comment by mondo989** [comment]
Box is now dynamic in height and can handle different sizes.

<img width="563" alt="screen shot 2016-04-19 at 11 39 53 pm" src="https://cloud.githubusercontent.com/assets/3431871/14662882/93fad944-0688-11e6-8ad6-fb2cf933e9f2.png">

**Comment by tomholub** [comment]
great!
